version: '3'

services:
  php:
    build: './backend'
    ports:
      - 5000:80
    volumes:
      - './backend:/var/www/html'
    networks:
      - postgres
  postgres:
    container_name: postgres_container2
    image: postgres:latest
    environment:
      POSTGRES_DB: "php2"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret_pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5433:5432"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - app-volume:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin_container2
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "super@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "rootPassword"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data2:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
volumes:
  pgadmin-data2:
  app-volume: